Title
houghj16/ShareX pull request #57
Opened 2024-01-25 21:19 UTC by houghj16

Description
- task 
- 1

#29

2024-02-09 19:26 UTC, houghj16 reviewed
Please disregard items 2 and 3 on the attached ticket, we'll be addressing those in a separate PR.

2024-02-09 19:26 UTC, houghj16 commented on SECURITY.md
> +2. Click on the "Report a vulnerability" button.
Comment for review

2024-02-09 19:26 UTC, houghj16 commented on SECURITY.md
> +We encourage you to play a crucial role in keeping our project secure, and we thank you for your contributions to the community.
Comment 2 for review

2024-02-09 19:31 UTC, otheruser16 approved these changes

2024-02-09 19:31 UTC, otheruser16 commented on ShareX/BalloonTipAction.cs
> +
Comment for review

2024-02-09 19:32 UTC, otheruser16 requested changes
Request changes

2024-02-09 19:32 UTC, otheruser16 commented on ShareX/EasterEggBounce.cs
> +
Comment for review

2024-03-13 22:12 UTC, houghj16 commented on SECURITY.md
> +We encourage you to play a crucial role in keeping our project secure, and we thank you for your contributions to the community.
Thanks!

2024-03-13 22:29 UTC, houghj16 commented on ShareX/BalloonTipAction.cs
> +
Add image Object

2024-03-13 22:31 UTC, houghj16 commented on SECURITY.md
> +We encourage you to play a crucial role in keeping our project secure, and we thank you for your contributions to the community.
Thanks!

2024-04-01 16:00 UTC, houghj16 commented on ShareX/Forms/QRCodeForm.cs
> +        public QRCodeFormItem(string text = null)
Use a more descriptive label for the text

2024-04-02 19:30 UTC, houghj16 commented on ShareX/Forms/QRCodeForm.Designer.cs
>          /// <summary>
Can we add more explanation here?

2024-04-02 21:46 UTC, otheruser16 commented on ShareX/BalloonTipAction.cs
> +        public object Image { get; set; }
can we use a different type for this image variable

2024-04-05 18:36 UTC, closed without merging